[package]

name = "chip8"
version = "0.0.2"
authors = [ "mikezaby@gmail.com", "Youssef Habri <youssef.habri@gmail.com>"  ]

[[bin]]
name = "chip8"
path = "src/main.rs"

[dependencies]
rand = "0.3"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"